# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/users.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.user.RequestType" do
  end
  add_message "protocol.user.User" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :age, :int64, 3
    optional :org, :string, 4
  end
end

module Protocol
  module User
    RequestType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.user.RequestType").msgclass
    User = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.user.User").msgclass
  end
end
