# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protocol/users.proto for package 'protocol.user'

require 'grpc'
require 'protocol/users_pb'

module Protocol
  module User
    module Users
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'protocol.user.Users'

        rpc :Create, User, User
        rpc :List, RequestType, stream(User)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
